[unity]
# 下面列出的是需要统一文本的内容，以方便后续统计
# 分为三大块：problemappearance、problemcause、solution，即问题现象、问题原因、解决方案
# 其中每大块又包括三部分：or、and、str
# or是同一含义不同表示的文本内容
    #键值对中的键是最终需要修改成的内容，值是一个列表，里面的内容用于筛选
# and是需要同时出现的文本内容，也是用于筛选
    #键值对中的键同上，值也是一个列表，需要注意的是有时候前面会加~，表示反向筛选，选出不包含这个字符串的，提高灵活性
# str是为了方便修改多问题的情况
    #键值对中的键同上，值是一个字符串，通常比较简洁

  [unity.problemappearance]
    # 注意先处理or的情况，例如先将所有包含不上电不通电的字符串都筛选出来
    [unity.problemappearance.or]
    不上电 = ['不上电', '不通电']
    4G不在线 = []
    无声音输出 = []
    网络不通 = ['网络不通', '无网络', '网络连不上']
    声音异常 = []
    搜索不到终端 = []
    不出串口 = ['不出串口', '不跳串口']
    电源指示灯不亮 = []
    网络指示灯不亮 = []
    不断重启 = []

    [unity.problemappearance.and]
    不上电 = ['~面板不上电']
    4G不在线 = ['不', '线', '~TS流', '~平台设备']
    无声音输出 = ['无声', '~喊话', '~USB', '~喇叭', '~监听', '~话筒', '~FM']
    网络不通 = []
    声音异常 = ['声音异常']
    搜索不到终端 = ['搜', '终端']
    不出串口 = []
    电源指示灯不亮 = ['电源', '不亮']
    网络指示灯不亮 = ['网络', '不亮']
    不断重启 = ['重启', '~U盘']

    [unity.problemappearance.str]
    不上电 = '电'
    4G不在线 = '线'
    无声音输出 = '声'
    网络不通 = '网络'
    声音异常 = '声音'
    搜索不到终端 = '终端'
    不出串口 = '串口'
    电源指示灯不亮 = '电源'
    网络指示灯不亮 = '灯'
    不断重启 = '重启'


  [unity.problemcause]
    [unity.problemcause.or]
    检测无问题 = []
    开关电源坏 = []
    通讯模块坏 = []
    功放芯片坏 = []
    网络芯片坏 = []
    SIM卡槽坏 = []
    FB2电感坏 = []

    [unity.problemcause.and]
    检测无问题 = ['检', '~SIM', '~研发']
    开关电源坏 = ['开关电源', '~扯离']
    通讯模块坏 = ['通讯', '~铜箔', '~U7', '~进水']
    功放芯片坏 = ['功放芯片']
    网络芯片坏 = ['网络芯片', '~8']
    SIM卡槽坏 = ['SIM', '氧化', '~指示灯']
    FB2电感坏 = ['FB2', '~烧']

    [unity.problemcause.str]
    检测无问题 = '检'
    开关电源坏 = '源'
    通讯模块坏 = '通讯'
    功放芯片坏 = '功放'
    网络芯片坏 = '网络'
    SIM卡槽坏 = 'SIM'
    FB2电感坏 = 'FB2'


  [unity.solution]
    [unity.solution.or]
    升级程序 = ['升级', '更新']
    更换网口座子RJ45 = []
    更换功放芯片MP7770 = ['MP770', 'MP7770']
    #4G天线处加绝缘垫片 = []

    [unity.solution.and]
    升级程序 = ['~底层', '~写入']
    更换网口座子RJ45 = ['RJ45']
    更换功放芯片MP7770 = []
    #4G天线处加绝缘垫片 = ['天线', '绝缘']

    [unity.solution.str]
    升级程序 = '程序'
    更换网口座子RJ45 = 'RJ45'
    更换功放芯片MP7770 = 'MP'
    #4G天线处加绝缘垫片 = '绝缘'
